"""Government Procurement and Government Finance domain blueprints.

Supports:
- Government Procurement (tenders, buyers, bidders, tender duration, procurement methods)
- Government Finance (budget, actual expenditure, allocations, execution rate)
"""
from __future__ import annotations

from app.domains.base import (
    ChartRule,
    ComparisonRule,
    DomainBlueprint,
    EntityRule,
    KpiRule,
    RecommendationRule,
    RiskRule,
    TrendRule,
)

DOMAINS: list[DomainBlueprint] = [
    DomainBlueprint(
        id="government_procurement",
        name="Government Procurement",
        description="Public sector tender solicitations, contract awards, procurement methods, bidder competition, buyer agency activity, and tender lifecycle duration.",
        keywords=(
            "tender",
            "procurement",
            "contract_value",
            "procurement_method",
            "tenderer",
            "bidder",
            "buyer",
            "contracting_authority",
            "tender_id",
            "award_date",
            "submission_deadline",
            "tender_duration",
            "bids_received",
            "supplier",
            "rfp",
            "rfq",
            "contract_no",
        ),
        alternative_domains=("Government Finance", "Supply Chain and Logistics", "General Business Analytics"),
        entities=(
            EntityRule("tender", "Tender / Solicitation", ("tender_id", "tender_no", "contract_id", "solicitation_id", "id")),
            EntityRule("buyer", "Buyer / Contracting Authority", ("buyer", "contracting_authority", "procuring_entity", "agency", "department", "ministry")),
            EntityRule("tenderer", "Supplier / Bidder", ("tenderer", "bidder", "supplier", "contractor", "vendor")),
        ),
        kpis=(
            KpiRule(
                "total_procurement_value",
                "Total Procurement Value",
                "Total monetary volume of awarded contracts and tenders",
                ("numeric",),
                metric_patterns=("tender_value", "contract_value", "award_value", "amount", "budget", "value"),
                formula="sum",
                format="currency",
                business_meaning="Aggregate public spending commitment",
            ),
            KpiRule(
                "total_tenders",
                "Total Tender Solicitations",
                "Count of distinct tender solicitations processed",
                ("numeric", "categorical", "identifier"),
                metric_patterns=("tender_id", "tender_no", "contract_id", "id"),
                formula="count_distinct",
                format="number",
                business_meaning="Total procurement transaction volume",
            ),
            KpiRule(
                "avg_tender_value",
                "Average Tender Value",
                "Mean monetary value per contract/tender",
                ("numeric",),
                metric_patterns=("tender_value", "contract_value", "award_value", "amount", "value"),
                formula="mean",
                format="currency",
                business_meaning="Typical contract size",
            ),
            KpiRule(
                "avg_tender_duration",
                "Average Tender Duration (Days)",
                "Mean elapsed days from publication/tender issue to submission/award",
                ("numeric",),
                metric_patterns=("tender_duration", "duration_days", "procurement_days", "lead_time_days", "duration"),
                formula="mean",
                format="duration",
                business_meaning="Procurement process velocity and administrative efficiency",
            ),
            KpiRule(
                "avg_bidders_per_tender",
                "Average Bidders per Tender",
                "Mean number of competing bids submitted per tender",
                ("numeric",),
                metric_patterns=("bids_received", "tenderer_count", "bidders_count", "bids", "bidders"),
                formula="mean",
                format="number",
                business_meaning="Market competition level in public procurement",
            ),
        ),
        charts=(
            ChartRule(
                "spend_by_buyer",
                "Procurement Spend by Buyer Agency",
                "bar",
                dimension_patterns=("buyer", "contracting_authority", "agency", "department", "ministry"),
                metric_patterns=("tender_value", "contract_value", "award_value", "amount", "value"),
                aggregation="sum",
                business_question="Which public agencies/departments account for the largest procurement spend?",
            ),
            ChartRule(
                "avg_duration_by_category",
                "Average Tender Duration by Category (Days)",
                "bar",
                dimension_patterns=("category", "procurement_category", "sector", "type", "goods_services"),
                metric_patterns=("tender_duration", "duration_days", "procurement_days", "duration"),
                aggregation="mean",
                business_question="Which procurement categories experience the longest administrative lead times? (Note: durations are compared as averages via bar chart, never part-to-whole)",
            ),
            ChartRule(
                "tenders_by_method",
                "Tenders by Procurement Method",
                "bar",
                dimension_patterns=("procurement_method", "method", "tender_type", "procedure"),
                metric_patterns=("tender_id", "tender_no", "id", "tender_value"),
                aggregation="count",
                business_question="What proportion of tenders use open vs restricted/direct procurement methods?",
            ),
            ChartRule(
                "duration_vs_value",
                "Tender Value vs Tender Duration",
                "scatter",
                dimension_patterns=(),
                metric_patterns=("tender_value", "tender_duration", "contract_value", "duration_days"),
                aggregation="sum",
                business_question="Do higher-value public tenders take longer to process and award?",
            ),
        ),
        comparisons=(
            ComparisonRule("category", "Procurement Spend across Agencies", ("buyer", "contracting_authority", "agency"), ("tender_value", "contract_value", "amount")),
            ComparisonRule("category", "Tender Duration by Procurement Method", ("procurement_method", "method"), ("tender_duration", "duration_days")),
        ),
        trends=(
            TrendRule(("tender_value", "contract_value", "amount"), ("award_date", "date", "publication_date", "year"), "Tracking public procurement expenditure over time"),
        ),
        risks=(
            RiskRule(
                "single_bidder_anomaly",
                "Low Competition Alert",
                "drop",
                metric_patterns=("bids_received", "tenderer_count", "bidders_count", "bids"),
                threshold=1.0,
                label="Requires investigation",
                recommended_action="Review tenders with only 1 bidder for potential anti-competitive specifications or insufficient notice.",
            ),
            RiskRule(
                "duration_outlier_delay",
                "Procurement Delay Outlier",
                "spike",
                metric_patterns=("tender_duration", "duration_days", "procurement_days"),
                threshold=180.0,
                label="Requires investigation",
                recommended_action="Examine tenders exceeding 180 days in duration for procedural bottlenecks.",
            ),
        ),
        recommendations=(
            RecommendationRule(
                "operational_efficiency",
                "avg_tender_duration",
                "extended_lead_times",
                "Standardize specification templates in categories with high tender durations to accelerate publication-to-award cycles.",
                "Subject to statutory public procurement review periods.",
            ),
            RecommendationRule(
                "cost_reduction",
                "avg_bidders_per_tender",
                "low_competition_tenders",
                "Broaden vendor outreach and publication channels for categories averaging fewer than 2 bidders.",
                "Subject to supplier market availability.",
            ),
        ),
    ),
    DomainBlueprint(
        id="government_finance",
        name="Government Finance",
        description="Public treasury finances, municipal and federal budgets, appropriations, actual expenditures, departmental allocations, and fiscal variance.",
        keywords=(
            "budget",
            "expenditure",
            "appropriation",
            "treasury",
            "fiscal_year",
            "allotment",
            "disbursement",
            "public_finance",
            "tax_revenue",
            "deficit",
            "fiscal_period",
            "actual_spend",
        ),
        alternative_domains=("Government Procurement", "Corporate Finance", "General Business Analytics"),
        entities=(
            EntityRule("appropriation", "Budget Line / Appropriation", ("appropriation_id", "budget_line", "account_code", "program")),
            EntityRule("department", "Ministry / Government Department", ("department", "ministry", "agency", "division")),
        ),
        kpis=(
            KpiRule(
                "total_budget",
                "Total Approved Budget",
                "Sum of authorized appropriations and budget allocations",
                ("numeric",),
                metric_patterns=("budget", "allocated_budget", "approved_budget", "appropriation"),
                formula="sum",
                format="currency",
                business_meaning="Total authorized public expenditure ceiling",
            ),
            KpiRule(
                "actual_expenditure",
                "Total Actual Expenditure",
                "Total executed disbursements and actual spending",
                ("numeric",),
                metric_patterns=("expenditure", "actual_spend", "actual_expenditure", "disbursement"),
                formula="sum",
                format="currency",
                business_meaning="Total public funds utilized",
            ),
            KpiRule(
                "budget_execution_rate",
                "Budget Execution Rate",
                "Actual expenditure divided by approved budget allocation",
                ("numeric",),
                metric_patterns=("execution_rate", "utilization_rate", "spend_pct"),
                formula="mean",
                format="percentage",
                business_meaning="Fiscal execution efficiency",
            ),
        ),
        charts=(
            ChartRule(
                "spend_by_department",
                "Expenditure by Department / Ministry",
                "bar",
                dimension_patterns=("department", "ministry", "agency"),
                metric_patterns=("expenditure", "actual_spend", "budget"),
                aggregation="sum",
                business_question="Which government departments consume the largest share of public expenditures?",
            ),
            ChartRule(
                "fiscal_trend",
                "Fiscal Spend Trajectory",
                "line",
                dimension_patterns=(),
                metric_patterns=("expenditure", "disbursement", "actual_spend"),
                aggregation="sum",
                business_question="How is public expenditure tracking against fiscal quarters and periods?",
            ),
        ),
        comparisons=(
            ComparisonRule("category", "Budget vs Actual by Department", ("department", "ministry"), ("budget", "expenditure")),
        ),
        trends=(
            TrendRule(("expenditure", "budget"), ("fiscal_year", "period", "date", "year"), "Tracking multi-year public expenditure trends"),
        ),
        risks=(
            RiskRule(
                "budget_overrun",
                "Budget Overrun Risk",
                "spike",
                metric_patterns=("expenditure", "variance"),
                threshold=1.0,
                label="Requires investigation",
                recommended_action="Audit departments with actual spending exceeding approved budget allocations.",
            ),
        ),
        recommendations=(
            RecommendationRule(
                "cost_reduction",
                "actual_expenditure",
                "budget_variance",
                "Implement quarterly milestone reviews for capital expenditure line items showing high variance.",
                "Subject to legislative fiscal mandates.",
            ),
        ),
    ),
]
